###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################

# automation:
# cloud:
counter:
dhcp:
# energy:
frontend:
  themes: !include_dir_merge_named themes
homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  allowlist_external_dirs: '/config/recordings'
history:
  exclude: 
    domains:
      - automation
      - updater
    entities:
      - sun.sun
    entity_globs:
      - binary_sensor.*_occupancy
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
# logbook:
# map:
# media_source:
# mobile_app:
my:
network:
panel_iframe:
  editor:
    title: 'Editor'
    icon: mdi:wrench
    url: 'https://hass.danhnguyen.nl/code-server/'
person:
recorder:
  db_url: !secret postgres_url
  purge_keep_days: 30
  commit_interval: 20
  exclude:
    domains:
      - automation
      - light
      - switch
      - script
    entity_globs:
      - binary_sensor.*_occupancy
    entities:
      - sun.sun
# scene:
# script:
ssdp:
stream:
sun:
system_health:
# tag:
timer:
tts:
  - platform: google_translate
# usb:
webhook:
zeroconf:
# zone:

####################################################
#                                                  #
#                     Devices                      #
#                                                  #
####################################################

camera:
  - platform: generic
    name: Hikvision
    verify_ssl: false
    username: !secret hikvision_user
    password: !secret hikvision_pwd
    still_image_url: !secret hikvision_image
    stream_source: !secret hikvision_rtsp
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token
    username: !secret email_address
    password: !secret xiamo_cloud_pw
    draw: ['all']
    auto_update: false
    attributes:
      - calibration_points    

binary_sensor:
  - platform: hikvision
    host: !secret hikvision_ip
    username: !secret hikvision_user
    password: !secret hikvision_pwd

google_assistant:
  project_id: hassio-213013
  service_account: !include HassIO-fe66053067fe.json
  report_state: true
  exposed_domains:
    - cover
    - camera
    - vacuum
    - light
    - switch
    - fan
    - climate
    - sensor
  entity_config:
    light.gateway_light_7811dcb8b670:
      expose: false
    light.0xccccccfffe8abc2f_light:
      expose: false
    light.0xccccccfffe58d568:
      expose: false
    light.0x14b457fffe9441f3_light:
      expose: false
    switch.0x04cf8cdf3c764470_switch:
      name: Couch light
    switch.0x04cf8cdf3c764398_switch:
      expose: false
    switch.zigbee2mqtt_main_join:
      expose: false
    light.0x842e14fffe16272d_light:
      expose: false
    light.0x00158d000403ca89_light:
      expose: false
    light.0x00158d0004313471_light:
      expose: false
    sensor.0x00158d00041880a0_action:
      expose: false
    light.xiaomi_philips_downlight:
      expose: false
    sensor.refrigerator_fridge_temp: 
      expose: false
    sensor.refrigerator_freezer_temp: 
      expose: false
    switch.refrigerator_express_mode:
      expose: false
    climate.refrigerator_freezer:
      expose: false
    climate.refrigerator_fridge:
      expose: false
    sensor.anna_setpoint:
      expose: false
    sensor.anna_outdoor_temperature:
      expose: false
    sensor.anna_temperature:
      expose: false
    sensor.0x04cf8cdf3c776d8b_temperature:
      expose: false
    switch.0x04cf8cdf3c776d8b_auto_off:
      expose: false
    switch.0x04cf8cdf3c764470_auto_off:
      expose: false
    switch.0x04cf8cdf3c764398_auto_off:
      expose: false
    light.0x04cd15fffe2cb254:
      expose: false
    light.0x04cd15fffe83df37:
      expose: false
    light.0x8cf681fffe13f806:
      expose: false

hacs:
  token: !secret hacs_token
  sidepanel_title: HACS
  sidepanel_icon: mdi:alpha-c-box

influxdb:
  host: !secret ion_pc_ip
  max_retries: 3
  default_measurement: state

light:
  - platform: group
    name: Dinner Lights
    entities:
      - light.0x14b457fffe9441f3_light
      - light.0xccccccfffe58d568
      - light.0xccccccfffe8abc2f_light
  - platform: group
    name: Kidsroom Ceiling Light
    entities:
      - light.0x04cd15fffe2cb254
      - light.0x04cd15fffe83df37
      - light.0x8cf681fffe13f806
  - platform: xiaomi_miio_philipslight
    name: Xiaomi Philips Downlight
    host: !secret xiaomi_philips_downlight_ip
    token: !secret xiaomi_philips_downlight_token
    model: philips.light.downlight

notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_group_id  

rdw:
  - plate: !secret kenteken_auto
    name: "Suzuki Swift"
    dateformat: '%d %b %Y'
    binary_sensors:
      - insured
    sensors:
      - expdate
      - recall

shell_command:
  magic_mirror_on: 'ssh pi@192.168.0.127 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i .ssh/id_rsa_rpi_display "/home/pi/scripts/on.sh"'
  magic_mirror_off: 'ssh pi@192.168.0.127 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i .ssh/id_rsa_rpi_display "/home/pi/scripts/off.sh"'

telegram_bot:
  - platform: polling
    api_key: !secret telegram_chat_token
    allowed_chat_ids:
      - !secret telegram_group_id

vacuum:
  - platform: miio2
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token
    name: Xiaomi Vacuum

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key

# remote:
#   - platform: xiaomi_miio
#     name: Xiaomi Universal Remote
#     host: 
#     token: !secret xiaomi_irremote_key

# xiaomi_miio_cooker:
#   name: Xiaomi Rice Cooker
#   host: 
#   token: !secret xiaomi_rice_key
#   model: chunmi.cooker.normal2

group: !include_dir_merge_named groups/
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
