###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################

default_config:
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  allowlist_external_dirs: '/config/recordings'
history:
  exclude:
    domains:
      - script
      - updater
      - zone
    entity_globs:
      - binary_sensor.*_battery
      - binary_sensor.*_update_available
      - binary_sensor.*_consumer_connected
      - sensor.battery_*
      - sensor.weather_*
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
panel_iframe:
  editor:
    title: 'Editor'
    icon: mdi:wrench
    url: !secret code_server
recorder:
  db_url: !secret postgres_url
  db_retry_wait: 15
  purge_keep_days: 30
  commit_interval: 20
  exclude:
    domains:
      - script
      - updater
      - zone
    entity_globs:
      - binary_sensor.*_battery
      - binary_sensor.*_update_available
      - binary_sensor.*_consumer_connected
      - sensor.battery_*
      - sensor.weather_*
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
    event_types:
      - call_service 
stream:
tts:
  - platform: google_translate

####################################################
#                                                  #
#                     Devices                      #
#                                                  #
####################################################

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token
    username: !secret email_address
    password: !secret xiamo_cloud_pw
    draw: ['all']
    auto_update: false
    attributes:
      - calibration_points

binary_sensor:
  - platform: hikvision
    host: !secret hikvision_ip
    username: !secret hikvision_user
    password: !secret hikvision_pwd

google_assistant:
  project_id: hassio-213013
  service_account: !include HassIO-fe66053067fe.json
  # api_key: !secret google_api
  report_state: true
  exposed_domains:
    - cover
    - camera
    - vacuum
    - light
    - switch
    - fan
    - climate
    - sensor
  entity_config:
    light.gateway_light_7811dcb8b670:
      expose: false
    sensor.smile_outdoor_temperature:
      expose: false
    light.0xccccccfffe8abc2f:
      expose: false
    light.0xccccccfffe58d568:
      expose: false
    light.0x14b457fffe9441f3:
      expose: false
    switch.0x04cf8cdf3c764470_switch:
      name: Couch light
    switch.0x04cf8cdf3c764398_switch:
      expose: false
    switch.zigbee2mqtt_main_join:
      expose: false
    light.0x842e14fffe16272d:
      expose: false
    light.0x00158d000403ca89:
      expose: false
    light.0x00158d0004313471:
      expose: false
    sensor.0x00158d00041880a0_action:
      expose: false
    light.ceiling_light:
      expose: false
    sensor.refrigerator_fridge_temp:
      expose: false
    sensor.refrigerator_freezer_temp:
      expose: false
    switch.refrigerator_express_mode:
      expose: false
    climate.refrigerator_freezer:
      expose: false
    climate.refrigerator_fridge:
      expose: false
    sensor.anna_setpoint:
      expose: false
    sensor.anna_outdoor_temperature:
      expose: false
    sensor.anna_temperature:
      expose: false
    sensor.0x04cf8cdf3c776d8b_temperature:
      expose: false
    switch.0x04cf8cdf3c776d8b_auto_off:
      expose: false
    switch.0x04cf8cdf3c764470_auto_off:
      expose: false
    switch.0x04cf8cdf3c764398_auto_off:
      expose: false
    light.0x04cd15fffe2cb254:
      expose: false
    light.0x04cd15fffe83df37:
      expose: false
    light.0x8cf681fffe13f806:
      expose: false
    switch.dmaker_1c_7af9_alarm:
      expose: false

hacs:
  token: !secret hacs_token
  sidepanel_title: HACS
  sidepanel_icon: mdi:alpha-c-box

notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_group_id

rdw:
  - plate: !secret kenteken_auto
    name: "Suzuki Swift"
    dateformat: '%d %b %Y'
    binary_sensors:
      - insured
    sensors:
      - expdate
      - recall

shell_command:
  magic_mirror_on: 'ssh pi@192.168.0.127 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/rpidisplay "/home/pi/scripts/on.sh"'
  magic_mirror_off: 'ssh pi@192.168.0.127 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/rpidisplay "/home/pi/scripts/off.sh"'

telegram_bot:
  - platform: polling
    api_key: !secret telegram_chat_token
    allowed_chat_ids:
      - !secret telegram_group_id

group: !include_dir_merge_named groups/
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
