- platform: template
  sensors:
    lg_fridge_door:
      value_template: >-
        {% if is_state("binary_sensor.refrigerator_door_open", "off") %}Closed{% else %}Open{% endif %}
    # airpurifier_aqi:
    #   friendly_name: Air Purifier Air Quality Index
    #   value_template: '{{ states.fan.mi_air_purifier_3_3h.attributes.aqi }}'
    #   icon_template: mdi:weather-windy
    # airpurifier_temperature:
    #   friendly_name: Air Purifier Temperature
    #   value_template: '{{ states.fan.mi_air_purifier_3_3h.attributes.temperature }}'
    #   unit_of_measurement: '°C'
    # airpurifier_humidity:
    #   friendly_name: Air Purifier Humidity
    #   value_template: '{{ states.fan.mi_air_purifier_3_3h.attributes.humidity }}'
    #   unit_of_measurement: '%'
    #   icon_template: mdi:water-percent
    # airpurifier_filter:
    #   friendly_name: Air Purifier Filter Life
    #   value_template: '{{ states.fan.mi_air_purifier_3_3h.attributes.filter_life_remaining }}'
    #   unit_of_measurement: '%'
    #   icon_template: mdi:filter
    # airpurifier_speed:
    #   friendly_name: Air Purifier Speed
    #   value_template: '{{ states.fan.mi_air_purifier_3_3h.attributes.motor_speed }}'
    #   unit_of_measurement: '%'
    #   icon_template: mdi:filter

- platform: mqtt
  name: Zigbee2mqtt Networkmap
  state_topic: zigbee2mqtt/bridge/networkmap/raw
  value_template: >-
    {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
  json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

- platform: dsmr_reader